version: '3'
services:
  db:
    image: postgres

  web:
    build: .
    volumes:
      - .:/myapp/
      - /bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
        #      - webpack-dev
    command: ./bin/rails s -p 3000 -b '0.0.0.0' 

  bundle:
    image: keto_trac_web
    command: echo bundling ruby gems??
    volumes:
      - /bundle

#  node_modules:
#    image: keto_trac_web
#    command: echo building node modules??
#    volumes: 
#      - /node_modules

#  webpack-dev:
#    image: keto_trac_web
#    build:
#      context: .
#    environment:
#      - NODE_ENV=development
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/myapp/
#    #command: ./bin/webpack-dev-server --host 0.0.0.0 --inline true --hot true
#    command: ./bin/webpack-dev-server --inline true --hot true
